version: '3'
services:
  user_service:
    build: ./user_service
    environment:
      - MONGO_URI=mongodb://mongo:27017/ecommerce
    depends_on:
      - mongo
    ports:
      - "5001:5001"

  product_service:
    build: ./product_service
    environment:
      - MONGO_URI=mongodb://mongo:27017/ecommerce
    depends_on:
      - mongo
    ports:
      - "5002:5002"

  order_service:
    build: ./order_service
    environment:
      - MONGO_URI=mongodb://mongo:27017/ecommerce
    depends_on:
      - mongo
    ports:
      - "5003:5003"

  payment_service:
    build: ./payment_service
    environment:
      - STRIPE_SECRET_KEY=your_stripe_secret_key
    depends_on:
      - mongo
    ports:
      - "5005:5005"

  authentication_service:
    build: ./authentication_service
    environment:
      - MONGO_URI=mongodb://mongo:27017/ecommerce
    depends_on:
      - mongo
    ports:
      - "5004:5004"

  api_gateway:
    build: ./api_gateway
    depends_on:
      - user_service
      - product_service
      - order_service
      - authentication_service
      - payment_service
    ports:
      - "5000:5000"

  mongo:
    image: mongo:latest
    volumes:
      - mongo-data:/data/db
    ports:
      - "27017:27017"

volumes:
  mongo-data:
